version: "3.8"


services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - s-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: paf

    ports:
      - "5432:5432"

    networks:
      - s-network

    volumes:
      - postgres-s-data:/var/lib/postgresql/data


networks:
  s-network:
    driver: bridge


volumes:
  postgres-s-data: